wait for dependency injected

diff --git a/abrouter b/abrouter
--- a/abrouter
+++ b/abrouter
@@ -5,6 +5,17 @@
 #
 set -e
 
+# wait for dependencies, abort after 60 seconds
+waitforlink 60
+if [ $? -ne 0]
+then
+  echo 'Link with dependencies failed' >&2
+  # i don't know what happens here, maybe the compose tries it again?
+  exit 1
+fi
+
+echo 'done waiting'
+
 . /usr/local/etc/abenv
 
 sqlauthrouter -d "${DSN}" -v
